events {}

http {
    log_format main '$remote_addr - $request_id [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_traceparent"';

    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        resolver 127.0.0.11 valid=10s ipv6=off;

        # Route /api/java/* -> SpringBoot
        location /api/java/ {
            set $upstream http://springboot-demo:8080;
            rewrite ^/api/java/(.*) /api/$1 break;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Request-ID $request_id;

            # W3C Trace Context propagation
            proxy_set_header traceparent $http_traceparent;
            proxy_set_header tracestate  $http_tracestate;

            add_header X-Request-ID $request_id always;
        }

        # Default -> FastAPI
        location / {
            set $upstream http://fastapi-demo:8000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Request-ID $request_id;

            # W3C Trace Context propagation
            proxy_set_header traceparent $http_traceparent;
            proxy_set_header tracestate  $http_tracestate;

            add_header X-Request-ID $request_id always;
        }
    }
}
