events {}
http {
    upstream fastapi {
        server fastapi-demo:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://fastapi;
            proxy_set_header Host $host;
        }
    }
}